import { Container } from '@mui/material';
import React from 'react';
import StepForm from './StepForm';

const Step2 = (props) => {
  return (
    <Container>
      <StepForm
        {...props}
        title='Interest'
        description={`This has to do with your knowledge of the end to end of a process, business or organization. You gain experience
        in your workspace, relationships or life situations that you have found yourself overtime.`}
        groupBy={(option) => option.category}
        multiple
        options={[
          { name: 'Acrobatics', category: 'Indoor' },
          { name: 'Acting', category: 'Indoor' },
          { name: 'Amateur radio', category: 'Indoor' },
          { name: 'Animation', category: 'Indoor' },
          { name: 'Aquascaping', category: 'Indoor' },
          { name: 'Astrology', category: 'Indoor' },
          { name: 'Baking', category: 'Indoor' },
          { name: 'Blogging', category: 'Indoor' },
          { name: 'Board/tabletop games', category: 'Indoor' },
          { name: 'Breadmaking', category: 'Indoor' },
          { name: 'Building', category: 'Indoor' },
          { name: 'Bullet journaling', category: 'Indoor' },
          { name: 'Cabaret', category: 'Indoor' },
          { name: 'Calligraphy', category: 'Indoor' },
          { name: 'Candle making', category: 'Indoor' },
          { name: 'Candy making', category: 'Indoor' },
          { name: 'Car fixing & building', category: 'Indoor' },
          { name: 'Card games', category: 'Indoor' },
          { name: 'Cardistry', category: 'Indoor' },
          { name: 'Cheesemaking', category: 'Indoor' },
          { name: 'Cleaning', category: 'Indoor' },
          { name: 'Clothesmaking', category: 'Indoor' },
          { name: 'Coffee roasting', category: 'Indoor' },
          { name: 'Collecting', category: 'Indoor' },
          { name: 'Coloring', category: 'Indoor' },
          { name: 'Computer programming', category: 'Indoor' },
          { name: 'Confectionery', category: 'Indoor' },
          { name: 'Cooking', category: 'Indoor' },
          { name: 'Cosplaying', category: 'Indoor' },
          { name: 'Couponing', category: 'Indoor' },
          { name: 'Craft', category: 'Indoor' },
          { name: 'Creative writing', category: 'Indoor' },
          { name: 'Crocheting', category: 'Indoor' },
          { name: 'Cross-stitch', category: 'Indoor' },
          { name: 'Cryptography', category: 'Indoor' },
          { name: 'Cue sports', category: 'Indoor' },
          { name: 'Dance', category: 'Indoor' },
          { name: 'Digital arts', category: 'Indoor' },
          { name: 'DJing', category: 'Indoor' },
          { name: 'Drama', category: 'Indoor' },
          { name: 'Drawing', category: 'Indoor' },
          { name: 'Drink mixing', category: 'Indoor' },
          { name: 'Drinking', category: 'Indoor' },
          { name: 'Electronic games', category: 'Indoor' },
          { name: 'Electronics', category: 'Indoor' },
          { name: 'Embroidery', category: 'Indoor' },
          { name: 'Experimenting', category: 'Indoor' },
          { name: 'Fantasy sports', category: 'Indoor' },
          { name: 'Fashion', category: 'Indoor' },
          { name: 'Fashion design', category: 'Indoor' },
          { name: 'Fishkeeping', category: 'Indoor' },
          { name: 'Filmmaking', category: 'Indoor' },
          { name: 'Flower arranging', category: 'Indoor' },
          { name: 'Fly tying', category: 'Indoor' },
          { name: 'Foreign language learning', category: 'Indoor' },
          { name: 'Furniture building', category: 'Indoor' },
          {
            name: 'Gaming (tabletop games and role-playing games)25',
            category: 'Indoor',
          },
          { name: 'Genealogy', category: 'Indoor' },
          { name: 'Gingerbread house making', category: 'Indoor' },
          { name: 'Glassblowing', category: 'Indoor' },
          { name: 'Graphic design', category: 'Indoor' },
          { name: 'Gunsmithing', category: 'Indoor' },
          { name: 'Gymnastics', category: 'Indoor' },
          { name: 'Hacking', category: 'Indoor' },
          { name: 'Herp keeping', category: 'Indoor' },
          { name: 'Home improvement', category: 'Indoor' },
          { name: 'Homebrewing', category: 'Indoor' },
          { name: 'Houseplant care', category: 'Indoor' },
          { name: 'Hula hooping', category: 'Indoor' },
          { name: 'Humor', category: 'Indoor' },
          { name: 'Hydroponics', category: 'Indoor' },
          { name: 'Ice skating', category: 'Indoor' },
          { name: 'Jewelry making', category: 'Indoor' },
          { name: 'Jigsaw puzzles', category: 'Indoor' },
          { name: 'Journaling', category: 'Indoor' },
          { name: 'Juggling', category: 'Indoor' },
          { name: 'Karaoke', category: 'Indoor' },
          { name: 'Karate', category: 'Indoor' },
          { name: 'Kendama', category: 'Indoor' },
          { name: 'Knife making', category: 'Indoor' },
          { name: 'Knitting', category: 'Indoor' },
          { name: 'Knot tying', category: 'Indoor' },
          { name: 'Kombucha brewing', category: 'Indoor' },
          { name: 'Lace making', category: 'Indoor' },
          { name: 'Lapidary', category: 'Indoor' },
          { name: 'Leather crafting', category: 'Indoor' },
          { name: 'Lego building', category: 'Indoor' },
          { name: 'Listening to music', category: 'Indoor' },
          { name: 'Listening to podcasts', category: 'Indoor' },
          { name: 'Lock picking', category: 'Indoor' },
          { name: 'Machining', category: 'Indoor' },
          { name: 'Macrame', category: 'Indoor' },
          { name: 'Magic', category: 'Indoor' },
          { name: 'Makeup', category: 'Indoor' },
          { name: 'Mazes (indoor/outdoor)', category: 'Indoor' },
          { name: 'Metalworking', category: 'Indoor' },
          { name: 'Model building', category: 'Indoor' },
          { name: 'Model engineering', category: 'Indoor' },
          { name: 'Nail art', category: 'Indoor' },
          { name: 'Needlepoint', category: 'Indoor' },
          { name: 'Origami', category: 'Indoor' },
          { name: 'Painting', category: 'Indoor' },
          { name: 'Palmistry', category: 'Indoor' },
          { name: 'Pet adoption & fostering', category: 'Indoor' },
          { name: 'Philately', category: 'Indoor' },
          { name: 'Photography', category: 'Indoor' },
          { name: 'Pilates', category: 'Indoor' },
          { name: 'Playing musical instruments', category: 'Indoor' },
          { name: 'Poi', category: 'Indoor' },
          { name: 'Pole dancing', category: 'Indoor' },
          { name: 'Pottery', category: 'Indoor' },
          { name: 'Powerlifting', category: 'Indoor' },
          { name: 'Practical jokes', category: 'Indoor' },
          { name: 'Pressed flower craft', category: 'Indoor' },
          { name: 'Puzzles', category: 'Indoor' },
          { name: 'Quilling', category: 'Indoor' },
          { name: 'Quilting', category: 'Indoor' },
          { name: 'Quizzes', category: 'Indoor' },
          { name: 'Radio-controlled model', category: 'Indoor' },
          { name: 'Rail transport modeling', category: 'Indoor' },
          { name: 'Rapping', category: 'Indoor' },
          { name: 'Reading', category: 'Indoor' },
          { name: 'Refinishing', category: 'Indoor' },
          { name: 'Reiki', category: 'Indoor' },
          { name: 'Robot combat', category: 'Indoor' },

          { name: 'Air sports', category: 'Outdoors' },
          { name: 'Airsoft', category: 'Outdoors' },
          { name: 'Amateur geology', category: 'Outdoors' },
          { name: 'Amusement park visiting', category: 'Outdoors' },
          { name: 'Archery', category: 'Outdoors' },
          { name: 'Astronomy', category: 'Outdoors' },
          { name: 'Backpacking', category: 'Outdoors' },
          { name: 'Badminton', category: 'Outdoors' },
          { name: 'Baseball', category: 'Outdoors' },
          { name: 'Basketball', category: 'Outdoors' },
          { name: 'Beekeeping', category: 'Outdoors' },
          { name: 'Birdwatching', category: 'Outdoors' },
          { name: 'Blacksmithing', category: 'Outdoors' },
          { name: 'BMX', category: 'Outdoors' },
          { name: 'Board sports', category: 'Outdoors' },
          { name: 'Bodybuilding', category: 'Outdoors' },
          { name: 'Bonsai', category: 'Outdoors' },
          { name: 'Butterfly watching', category: 'Outdoors' },
          { name: 'Bus riding', category: 'Outdoors' },
          { name: 'Camping', category: 'Outdoors' },
          { name: 'Canoeing', category: 'Outdoors' },
          { name: 'Canyoning', category: 'Outdoors' },
          { name: 'Car riding', category: 'Outdoors' },
          { name: 'Caving', category: 'Outdoors' },
          { name: 'Composting', category: 'Outdoors' },
          { name: 'Cycling', category: 'Outdoors' },
          { name: 'Dowsing', category: 'Outdoors' },
          { name: 'Driving', category: 'Outdoors' },
          { name: 'Farming', category: 'Outdoors' },
          { name: 'Fishing', category: 'Outdoors' },
          { name: 'Flag football', category: 'Outdoors' },
          { name: 'Flower growing', category: 'Outdoors' },
          { name: 'Flying', category: 'Outdoors' },
          { name: 'Flying disc', category: 'Outdoors' },
          { name: 'Foraging', category: 'Outdoors' },
          { name: 'Fossicking', category: 'Outdoors' },
          { name: 'Freestyle football', category: 'Outdoors' },
          { name: 'Gardening', category: 'Outdoors' },
          { name: 'Geocaching', category: 'Outdoors' },
          { name: 'Ghost hunting', category: 'Outdoors' },
          { name: 'Gold prospecting', category: 'Outdoors' },
          { name: 'Graffiti', category: 'Outdoors' },
          { name: 'Handball', category: 'Outdoors' },
          { name: 'Herbalism', category: 'Outdoors' },
          { name: 'Herping', category: 'Outdoors' },
          { name: 'High-power rocketry', category: 'Outdoors' },
          { name: 'Hiking', category: 'Outdoors' },
          { name: 'Hobby horsing', category: 'Outdoors' },
          { name: 'Hobby tunneling', category: 'Outdoors' },
          { name: 'Hooping', category: 'Outdoors' },
          { name: 'Horseback riding', category: 'Outdoors' },
          { name: 'Hunting', category: 'Outdoors' },
          { name: 'Inline skating', category: 'Outdoors' },
          { name: 'Jogging', category: 'Outdoors' },
          { name: 'Jumping rope', category: 'Outdoors' },
          { name: 'Kayaking', category: 'Outdoors' },
          { name: 'Kite flying', category: 'Outdoors' },
          { name: 'Kitesurfing', category: 'Outdoors' },
          { name: 'Lacrosse', category: 'Outdoors' },
          { name: 'LARPing', category: 'Outdoors' },
          { name: 'Letterboxing', category: 'Outdoors' },
          { name: 'Longboarding', category: 'Outdoors' },
          { name: 'Martial arts', category: 'Outdoors' },
          { name: 'Metal detecting', category: 'Outdoors' },
          { name: 'Meteorology', category: 'Outdoors' },
          { name: 'Motor sports', category: 'Outdoors' },
          { name: 'Mountain biking', category: 'Outdoors' },
          { name: 'Mountaineering', category: 'Outdoors' },
          { name: 'Museum visiting', category: 'Outdoors' },
          { name: 'Mushroom hunting/mycology', category: 'Outdoors' },
          { name: 'Netball', category: 'Outdoors' },
          { name: 'Nordic skating', category: 'Outdoors' },
          { name: 'Orienteering', category: 'Outdoors' },
          { name: 'Paintball', category: 'Outdoors' },
          { name: 'Parkour', category: 'Outdoors' },
          { name: 'Photography', category: 'Outdoors' },
          { name: 'Podcast hosting', category: 'Outdoors' },
          { name: 'Polo', category: 'Outdoors' },
          { name: 'Public transport riding', category: 'Outdoors' },
          { name: 'Rafting', category: 'Outdoors' },
          { name: 'Railway journeys', category: 'Outdoors' },
          { name: 'Rappelling', category: 'Outdoors' },
          { name: 'Road biking', category: 'Outdoors' },
          { name: 'Rock climbing', category: 'Outdoors' },
          { name: 'Roller skating', category: 'Outdoors' },
          { name: 'Rugby', category: 'Outdoors' },
          { name: 'Running', category: 'Outdoors' },
          { name: 'Radio-controlled model', category: 'Outdoors' },
          { name: 'Sailing', category: 'Outdoors' },
          { name: 'Sand art', category: 'Outdoors' },
          { name: 'Scouting', category: 'Outdoors' },
          { name: 'Scuba diving', category: 'Outdoors' },
          { name: 'Sculling or rowing', category: 'Outdoors' },
          { name: 'Shooting', category: 'Outdoors' },
          { name: 'Shopping', category: 'Outdoors' },
          { name: 'Shuffleboard', category: 'Outdoors' },
          { name: 'Skateboarding', category: 'Outdoors' },
          { name: 'Skiing', category: 'Outdoors' },
          { name: 'Skimboarding', category: 'Outdoors' },
          { name: 'Skydiving', category: 'Outdoors' },
          { name: 'Slacklining', category: 'Outdoors' },
          { name: 'Snowboarding', category: 'Outdoors' },
          { name: 'Snowmobiling', category: 'Outdoors' },
          { name: 'Snowshoeing', category: 'Outdoors' },
          { name: 'Soccer', category: 'Outdoors' },
          { name: 'Stone skipping', category: 'Outdoors' },
          { name: 'Sun bathing', category: 'Outdoors' },
          { name: 'Surfing', category: 'Outdoors' },
          { name: 'Survivalism', category: 'Outdoors' },
          { name: 'Swimming', category: 'Outdoors' },
          { name: 'Taekwondo', category: 'Outdoors' },
          { name: 'Tai chi', category: 'Outdoors' },
          { name: 'Tennis', category: 'Outdoors' },
          { name: 'Topiary', category: 'Outdoors' },
          { name: 'Tourism', category: 'Outdoors' },
          { name: 'Thru-hiking', category: 'Outdoors' },
          { name: 'Trade fair visiting', category: 'Outdoors' },
          { name: 'Travel', category: 'Outdoors' },
          { name: 'Urban exploration', category: 'Outdoors' },
          { name: 'Vacation', category: 'Outdoors' },
          { name: 'Vegetable farming', category: 'Outdoors' },
          { name: 'Videography', category: 'Outdoors' },
          { name: 'Vehicle restoration', category: 'Outdoors' },
          { name: 'Walking', category: 'Outdoors' },
          { name: 'Water sports', category: 'Outdoors' },

          { name: 'Astronomy', category: 'Educational' },
          { name: 'Biology', category: 'Educational' },
          { name: 'Chemistry', category: 'Educational' },
          { name: 'Electrochemistry', category: 'Educational' },
          { name: 'Geography', category: 'Educational' },
          { name: 'History', category: 'Educational' },
          { name: 'Mathematics', category: 'Educational' },
          { name: 'Psychology', category: 'Educational' },
          { name: 'Physics', category: 'Educational' },
          { name: 'Railway studies', category: 'Educational' },
          { name: 'Science and technology studies', category: 'Educational' },
          { name: 'Social studies', category: 'Educational' },
          { name: 'Sports science', category: 'Educational' },
          { name: 'Collection hobbies', category: 'Educational' },
          { name: 'Indoorsedit', category: 'Educational' },
          { name: 'Action figure', category: 'Educational' },
          { name: 'Antiquing', category: 'Educational' },
          { name: 'Ant-keeping', category: 'Educational' },
          { name: 'Art collecting', category: 'Educational' },
          { name: 'Book collecting', category: 'Educational' },
          { name: 'Button collecting', category: 'Educational' },
          { name: 'Cartophily (card collecting)', category: 'Educational' },
          { name: 'Coin collecting', category: 'Educational' },
          { name: 'Comic book collecting', category: 'Educational' },
          { name: 'Deltiology (postcard collecting)', category: 'Educational' },
          { name: 'Die-cast toy', category: 'Educational' },
          { name: 'Digital hoarding', category: 'Educational' },
          { name: 'Dolls', category: 'Educational' },
          { name: 'Element collecting', category: 'Educational' },
          { name: 'Ephemera collecting', category: 'Educational' },
          {
            name: 'Fusilately (phonecard collecting)',
            category: 'Educational',
          },
          { name: 'Knife collecting', category: 'Educational' },
          {
            name: 'Lotology (lottery ticket collecting)',
            category: 'Educational',
          },
          {
            name: 'Movie and movie memorabilia collecting',
            category: 'Educational',
          },
          { name: 'Fingerprint collecting', category: 'Educational' },
          { name: 'Perfume', category: 'Educational' },
          { name: 'Phillumeny', category: 'Educational' },
          { name: 'Pin (lapel)', category: 'Educational' },
          { name: 'Radio-controlled model', category: 'Educational' },
          { name: 'Rail transport modeling', category: 'Educational' },
          { name: 'Record collecting', category: 'Educational' },
          { name: 'Rock tumbling', category: 'Educational' },
          { name: 'Scutelliphily', category: 'Educational' },
          { name: 'Shoes', category: 'Educational' },
          { name: 'Slot car', category: 'Educational' },
          { name: 'Sports memorabilia', category: 'Educational' },
          { name: 'Stamp collecting', category: 'Educational' },
          { name: 'Stuffed toy collecting', category: 'Educational' },
          { name: 'Tea bag collecting', category: 'Educational' },
          { name: 'Ticket collecting', category: 'Educational' },
          { name: 'Toys', category: 'Educational' },
          { name: 'Transit map collecting', category: 'Educational' },
          { name: 'Video game collecting', category: 'Educational' },
          { name: 'Vintage cars', category: 'Educational' },
          { name: 'Vintage clothing', category: 'Educational' },
          { name: 'Vinyl Records', category: 'Educational' },
          { name: 'Outdoorsedit', category: 'Educational' },
          { name: 'Antiquities', category: 'Educational' },
          { name: 'Auto audiophilia', category: 'Educational' },
          { name: 'Flower collecting and pressing', category: 'Educational' },
          { name: 'Fossil hunting', category: 'Educational' },
          { name: 'Insect collecting', category: 'Educational' },
          { name: 'Magnet fishing', category: 'Educational' },
          { name: 'Metal detecting', category: 'Educational' },
          { name: 'Mineral collecting', category: 'Educational' },
          { name: 'Rock balancing', category: 'Educational' },
          { name: 'Sea glass collecting', category: 'Educational' },
          { name: 'Seashell collecting', category: 'Educational' },
          { name: 'Stone collecting', category: 'Educational' },
          { name: 'Competitive hobbies', category: 'Educational' },
          { name: 'Indoors', category: 'Educational' },
          { name: 'Animal fancy', category: 'Educational' },
          { name: 'Axe throwing', category: 'Educational' },
          { name: 'Backgammon', category: 'Educational' },
          { name: 'Badminton', category: 'Educational' },
          { name: 'Baton twirling', category: 'Educational' },
          { name: 'Beauty pageants', category: 'Educational' },
          { name: 'Billiards', category: 'Educational' },
          { name: 'Bowling', category: 'Educational' },
          { name: 'Boxing', category: 'Educational' },
          { name: 'Bridge', category: 'Educational' },
          { name: 'Checkers (draughts)', category: 'Educational' },
          { name: 'Cheerleading', category: 'Educational' },
          { name: 'Chess', category: 'Educational' },
          { name: 'Color guard', category: 'Educational' },
          { name: 'Cribbage', category: 'Educational' },
          { name: 'Curling', category: 'Educational' },
          { name: 'Dancing', category: 'Educational' },
          { name: 'Darts', category: 'Educational' },
          { name: 'Debate', category: 'Educational' },
          { name: 'Dominoes', category: 'Educational' },
          { name: 'Eating', category: 'Educational' },
          { name: 'Esports', category: 'Educational' },
          { name: 'Fencing', category: 'Educational' },
          { name: 'Go', category: 'Educational' },
          { name: 'Gymnastics', category: 'Educational' },
          { name: 'Ice hockey', category: 'Educational' },
          { name: 'Ice skating', category: 'Educational' },
          { name: 'Judo', category: 'Educational' },
          { name: 'Jujitsu', category: 'Educational' },
          { name: 'Kabaddi', category: 'Educational' },
          { name: 'Knowledge/word games', category: 'Educational' },
          { name: 'Laser tag', category: 'Educational' },
          { name: 'Longboarding', category: 'Educational' },
          { name: 'Mahjong', category: 'Educational' },
          { name: 'Marbles', category: 'Educational' },
          { name: 'Martial arts', category: 'Educational' },
          { name: 'Model racing', category: 'Educational' },
          { name: 'Model United Nations', category: 'Educational' },
          { name: 'Poker', category: 'Educational' },
          { name: 'Pole dancing', category: 'Educational' },
          { name: 'Pool', category: 'Educational' },
          { name: 'Role-playing games', category: 'Educational' },
          { name: 'Shogi', category: 'Educational' },
          { name: 'Slot car racing', category: 'Educational' },
          { name: 'Speedcubing', category: 'Educational' },
          { name: 'Sport stacking', category: 'Educational' },
          { name: 'Table football', category: 'Educational' },
          { name: 'Table tennis', category: 'Educational' },
          { name: 'Volleyball', category: 'Educational' },
          { name: 'Weightlifting', category: 'Educational' },
          { name: 'Wrestling', category: 'Educational' },
        ]}
      />
    </Container>
  );
};

export default Step2;
